#!/bin/bash

# Nom Extensio Nombre Ruta

error() {
    echo $1
    exit 1
}

if [ $1 == "--help" ]; then
    echo -e "---Creador de fitxers---\n Ús: $0 Nom Extensio Nombre Ruta"
    exit 1
elif [ $# -ne 4 ]; then
    error "Error d'ús: $0 Nom Extensio Nombre Ruta"
fi

if [ ! -d $4 ]; then
    error "Error: el directori no existeix"
fi

if [ $3 -lt 1 ]; then
    error "Error: el nombre de fichers no pot ser mes petit que 1"
fi

for (( i = 1; i <= $3; i++ )); do
    name="$4/$1$i$2"
    if [ $i -lt 10 ]; then
        name="$4/$10$i$2"
    fi
    touch $name
    echo "Fitxer $name creat" | tr -s /
done

