#!/bin/bash

# Prefix Nombre Ruta

error() {
    echo $1
    exit 1
}

createfol() {
    num_baix=`echo $2 | cut -d "-" -f 1`
    num_alt=`echo $2 | cut -d "-" -f 2`

    for (( i = $num_baix; i <= $num_alt; i++ )); do
        name="$3/$1$i"
        if [ $i -lt 10 ]; then
          name="$3/$10$i"
        fi
        mkdir $name
    done
}
foldoc() {
    # for (( i = 1; i <= `cat $2 | wc -l`; i++ )); do
    #     echo hello$i
    # done
    while IFS= read -r line
    do
        if [[ $line == -* ]]; then
            line=`echo $line | sed "s/-//"`
        elif [[ $line == ·* ]]; then
            line=`echo $line | sed "s/·//"`
        fi
        mkdir $1$line
    done < $2
}

if [ $# -eq 0 ]; then
        echo -n "Ruta: "
        read Ruta
        echo -n "Prefixe: "
        read Pref
        echo $Pref
        if [[ Pref == "doc "]]; then
            echo -n "Document: "
            read Doc
            foldoc "$Ruta" "$Doc"
        else
            echo -n "Rang(Principi-Final): "
            read Rang
            createfol "$Pref" "$Rang" "$Ruta"
        fi
elif [ -f "$1" ]; then
    foldoc "$2" "$1"
else
    if [ $1 == "--help" ]; then
        echo -e "---Creador de fitxers--- \n Ús: FolderOne Prefix Rang Ruta"
        exit 1
    else
        if [ ! -d $3 ]; then
           error "Error: el directori no existeix"
        fi

        #if [ $2 -lt 1 ]; then
        #    error "Error: el nombre de fichers no pot ser mes petit que 1"
        #fi
    fi
    createfol "$1" "$2" "$3"
fi
if [ $1 == "-p" -o $1 == "--preset" ]; then
    echo "Ceating Preset"
fi
echo "Fitxers creats correctament!"